language: php

php:
  - 7.1
  - 7.2

before_script:
  - printf 'yes\nno\nyes\nno\nno\nno\n' | pecl install swoole
  - echo "extension=swoole.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install

script: ./vendor/bin/phpunit -c phpunit.xml
